replicaCount: 2

image:
  repository: REPLACE_WITH_ACR/pagamento
  tag: latest
  pullPolicy: Always

service:
  port: 8080

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: pagamento.dorigao.dev.br
      paths:
        - path: /
          pathType: Prefix

env:
  - name: OTEL_SERVICE_NAME
    value: "pagamento"
  - name: OTEL_EXPORTER_OTLP_ENDPOINT
    value: "http://alloy.observability.svc.cluster.local:4318"
  - name: DEPLOY_ENV
    value: "production"
  - name: LOG_LEVEL
    value: "INFO"
  - name: SERVER_PORT
    value: "8080"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /health/liveness
    port: 8080
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health/readiness
    port: 8080
  initialDelaySeconds: 10
  periodSeconds: 5

podLabels:
  app: pagamento
  app.kubernetes.io/name: pagamento
